### PR TITLE
Add module bays and module types.

### PR DESCRIPTION
**Pull request by dmcken**
Adds support for importing the device type module-bays.

Requires IMPORT_MODULES=True to be set for the code to activate (was debating if to detect automatically from the netbox version).

Will do the module-types in a separate pull request.

### CODE REVIEW

**Comment by ndom91** [comment]
I'd say your safe defaulting to module-types enabled, no? My opinion is this should always be up-to-date and working with the latest Netbox version. No need for extra backward compatibility. 

But that's just my opinion, maybe @minitriga sees it differently

**Comment by dmcken** [comment]
I am fine with it either way.

I guess once its tested a bit more we can change the default later on.

**Comment by dmcken** [comment]
Fully functional, importing modules as well now.

Did a complete import on a fresh 3.3.2 (latest docker image).

**Comment by ndom91** [comment]
When you're ready, don't forget to set it out of draft and "ready to review" and tag @minitriga as reviewer 👍

**Comment by dmcken** [comment]
Just doing some minor cleanup and want to test it against 3.2 before I finalize.

Just removed the manual setting, it will automatically detect the version to figure out if to sync modules or not.

**Comment by dmcken** [comment]
Ok, so 3.2.9 is working (I still use it as some plugins I use aren't ready for 3.3 yet).

The final result of a sync at the moment:
```
Script took 0:16:17.233122 to run
1724 devices created
42593 interfaces/ports updated
89 manufacturers created
141 modules created
1657 module interface / ports created
```

**Comment by ndom91** [comment]
Awesome, thanks! I'd also recommend updating the "tested with...3.2" towards the top of the README 👍

**Comment by dmcken** [comment]
I can't change the reviewer at the moment.

The option to link / close matching issues isn't available either so I assume thats something only the repo owners / maintainers can do.

**Comment by minitriga** [comment]
Thank you very much for this work. Looks good. Yes we should default to latest version of Netbox. I'm not interested in backwards compatibility for this project. Thank you @ndom91 @dmcken

**Pull request merged**
