### PR TITLE
docker build  + add vendors choices as env var

### PR DESCRIPTION
**Pull request by k0rventen**
Hi,

This PR adds a Dockerfile making possible to run the project as a container. 
It also enables the selection of vendors through an `VENDORS` env var, with the same behavior as the `--vendors` arg, so that everything is configurable through env var. 

Regarding the documentation, I think a new section could be added, but I wanted to check if you were ok with the feature beforehand. 

thx!

### CODE REVIEW

**Comment by ndom91** [comment]
Looks good to me! I'm sure @minitriga will approve as well. This is great for people who (gasp! haha) may not have a local installation of python.

**Comment by k0rventen** [comment]
Thx @ndom91 ! I've added the docker specific documentation. 

Would it be possible to also host this image on a container registry ?
I'm willing to setup the CI required.

**Comment by minitriga** [comment]
If you want to setup the CI required with Github actions then we can get something hosted yes.

**Comment by minitriga** [comment]
Sorry $dayjob has me very busy working on other things right now so I try to look when i can. Thanks for all the good work @k0rventen and @ndom91

**Pull request merged**
